### ISSUE TITLE
several functions depend on agency_id, which is an optional field

### ISSUE THREAD

**Issue by murcoil** [ropenscilabs/gtfsr#8]
I'm running into trouble with several of the mapping functions since they depend on the presence of agency_id, which is an optional field in agency.txt and routes.txt. So even though structure, files, and vars may validate, they can't necessarily be mapped. 

In Chicago, for example, CTA doesn't provide agency_id in its feed, so map_gtfs_route_shape() map_gtfs_route_stops() and map_gtfs_agency_routes() all fail.

A workaround is to add agency_id columns and fill them with dummy values (has to be the same for both agency_df and routes_df): 

> gtfs_objs$agency_df$agency_id <- "CTA"
> gtfs_objs$routes_df$agency_id <- "CTA"

(This gets complicated if you have more than a couple of elements in a list)

As a fix, maybe as part of the validation, just fill agency_id with some derived value if it's not present?

**Comment by dantonnoriega** [comment]
Great catch. `agency_name` is required but not `agency_id` --- which is different for other ID vars (like `stop_id`).

I'll change it to be so that it depends on `agency_name`.

**Comment by dantonnoriega** [comment]
OK! The input is now `agency_name` values. I still need to input some checks but it should be working. Note that the default is `agency = NULL` for the `map_gtfs_agency_routes` which means the function _assumes_ there is only one agency and takes the first observe `agency_name` by default.

[Here is a gist](https://gist.github.com/ultinomics/41be8cb0165a5b536e1e81762c74b1c5) for plotting CTA using the version I just pushed.

Let me know if it works and I'll close the issue.

**Comment by murcoil** [comment]
Still wasn't doing it for me--map_gtfs_agency_routes is choking on checking for a null value of agency_id rather than existence of the variable. I think I might have fixed it, if you take pull requests.

**Comment by murcoil** [comment]
I believe this is fixed by PR #9

**Comment by murcoil** [comment]
Thanks for catching names(), my mistake. Your new commit works for me. 

With the is.null() test I was still getting an error when the agency_id variable did not exist. My understanding of is.null() is that is looks at whether the content of the variable is null, but it assumes the variable exists.

`> "route_id" %in% names(gtfs_obj$routes_df) #variable exists
[1] TRUE

> "agency_id" %in% names(gtfs_obj$routes_df) #variable doesn't exist
> [1] FALSE
> is.null(gtfs_obj$routes_df$route_id)
> [1] FALSE
> is.null(gtfs_obj$routes_df$agency_id)
> Error: Unknown column 'agency_id'
> `
